server:
  port: 8080
#数据库相关
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dreamatach.com:3306/quartz?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: dream@2018.
    druid:
      max-active: 5
      initial-size: 2
      max-wait: 10000
      min-idle: 2
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
      validation-query: SELECT 1
  #    tomcat:
#      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)
  #rabbitmq配置
  rabbitmq:
    host: dreamatach.com
    port: 5672
    username: admin
    password: dadmin
    virtual-host: /
  #redis配置
  redis:
    database: 0
    host: dreamatach.com
    password: dreamatach.com
    jedis:
      pool:
        max-active: 5
        max-idle: 12
        max-wait: -1
        min-idle: 8
    port: 6379
    timeout: 0
#  #quartz相关属性配置
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true # 集群环境,只有一台机器会执行该任务
            clusterCheckinInterval: 10000
            useProperties: false
            dataSource: quartzDs
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: JDBC
    #初始化表结构
    jdbc:
      initialize-schema: NEVER
  #elasticsearch配置
  data:
    elasticsearch:
      cluster-name: zolbon
      cluster-nodes: 192.168.1.110:9300
      repositories:
        enabled: true